pages = [{"l":"index.html#","e":false,"i":"","n":"ProblemUtils","t":"ProblemUtils","d":"","k":"static","x":""},
{"l":"problemutils.html#","e":false,"i":"","n":"problemutils","t":"problemutils","d":"","k":"package","x":""},
{"l":"problemutils.html#Axis-0","e":false,"i":"","n":"Axis","t":"Axis: Axis.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Cardinal-0","e":false,"i":"","n":"Cardinal","t":"Cardinal = Cardinal","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Cardinal-0","e":false,"i":"","n":"Cardinal","t":"Cardinal: Cardinal.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#DisjointSets-0","e":false,"i":"","n":"DisjointSets","t":"DisjointSets[V] = DisjointSets[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#DisjointSets-0","e":false,"i":"","n":"DisjointSets","t":"DisjointSets: DisjointSets.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Edge-0","e":false,"i":"","n":"Edge","t":"Edge[V] = Edge[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Edge-0","e":false,"i":"","n":"Edge","t":"Edge: Edge.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#FiniteGraph-0","e":false,"i":"","n":"FiniteGraph","t":"FiniteGraph[V] = FiniteGraph[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#FiniteGraph-0","e":false,"i":"","n":"FiniteGraph","t":"FiniteGraph: FiniteGraph.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Graph-0","e":false,"i":"","n":"Graph","t":"Graph[V] = Graph[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Graph-0","e":false,"i":"","n":"Graph","t":"Graph: Graph.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Hex-0","e":false,"i":"","n":"Hex","t":"Hex = Hex","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Hex-0","e":false,"i":"","n":"Hex","t":"Hex: Hex.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#LazyGraph-0","e":false,"i":"","n":"LazyGraph","t":"LazyGraph[V] = LazyGraph[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#LazyGraph-0","e":false,"i":"","n":"LazyGraph","t":"LazyGraph: LazyGraph.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Matrix-0","e":false,"i":"","n":"Matrix","t":"Matrix[A] = Matrix[A]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Matrix-0","e":false,"i":"","n":"Matrix","t":"Matrix: Matrix.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Path-0","e":false,"i":"","n":"Path","t":"Path[V] = Path[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Path-0","e":false,"i":"","n":"Path","t":"Path: Path.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Pos2D-0","e":false,"i":"","n":"Pos2D","t":"Pos2D = Vec2","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Pos3D-0","e":false,"i":"","n":"Pos3D","t":"Pos3D = Vec3","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#ProceduralGraph-0","e":false,"i":"","n":"ProceduralGraph","t":"ProceduralGraph[V] = ProceduralGraph[V]","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#ProceduralGraph-0","e":false,"i":"","n":"ProceduralGraph","t":"ProceduralGraph: ProceduralGraph.type","d":"problemutils","k":"val","x":""},
{"l":"problemutils.html#Vec2-0","e":false,"i":"","n":"Vec2","t":"Vec2 = (Int, Int)","d":"problemutils","k":"type","x":""},
{"l":"problemutils.html#Vec3-0","e":false,"i":"","n":"Vec3","t":"Vec3 = (Int, Int, Int)","d":"problemutils","k":"type","x":""},
{"l":"problemutils/classes.html#","e":false,"i":"","n":"problemutils.classes","t":"problemutils.classes","d":"","k":"package","x":""},
{"l":"problemutils/classes/graphs.html#","e":false,"i":"","n":"problemutils.classes.graphs","t":"problemutils.classes.graphs","d":"","k":"package","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#","e":false,"i":"","n":"DisjointSets","t":"DisjointSets[V](var nodes: V*)","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#add-fffff71f","e":false,"i":"","n":"add","t":"add(v: V): Unit","d":"problemutils.classes.graphs.DisjointSets","k":"def","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#findSet-d26","e":false,"i":"","n":"findSet","t":"findSet(v: V): V","d":"problemutils.classes.graphs.DisjointSets","k":"def","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#makeUnion-ef2","e":false,"i":"","n":"makeUnion","t":"makeUnion(a: V, b: V): Unit","d":"problemutils.classes.graphs.DisjointSets","k":"def","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#parents-0","e":false,"i":"","n":"parents","t":"parents: Map[V, V]","d":"problemutils.classes.graphs.DisjointSets","k":"val","x":""},
{"l":"problemutils/classes/graphs/DisjointSets.html#rank-0","e":false,"i":"","n":"rank","t":"rank: Map[V, Int]","d":"problemutils.classes.graphs.DisjointSets","k":"val","x":""},
{"l":"problemutils/classes/graphs/DisjointSets$.html#","e":false,"i":"","n":"DisjointSets","t":"DisjointSets","d":"problemutils.classes.graphs","k":"object","x":""},
{"l":"problemutils/classes/graphs/DisjointSets$.html#from-fffffa9b","e":false,"i":"","n":"from","t":"from[V](nodes: Iterable[V]): DisjointSets[V]","d":"problemutils.classes.graphs.DisjointSets","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#","e":false,"i":"","n":"DynamicGraph","t":"DynamicGraph[V](using val adjacencyFunction: V => Set[Edge[V]]) extends Graph[V]","d":"problemutils.classes.graphs","k":"trait","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#adjacencyFunction-0","e":false,"i":"","n":"adjacencyFunction","t":"adjacencyFunction: V => Set[Edge[V]]","d":"problemutils.classes.graphs.DynamicGraph","k":"given","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#diff-fffff920","e":false,"i":"","n":"diff","t":"diff(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#excl-fffffde7","e":false,"i":"","n":"excl","t":"excl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#filterEdges-838","e":false,"i":"","n":"filterEdges","t":"filterEdges(p: Edge[V] => Boolean): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#filterVertices-838","e":false,"i":"","n":"filterVertices","t":"filterVertices(p: V => Boolean): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#given_DynamicGraph_V-0","e":false,"i":"","n":"given_DynamicGraph_V","t":"given_DynamicGraph_V: DynamicGraph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"given","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#incl-fffffde7","e":false,"i":"","n":"incl","t":"incl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#intersect-fffff920","e":false,"i":"","n":"intersect","t":"intersect(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/DynamicGraph.html#union-fffff920","e":false,"i":"","n":"union","t":"union(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.DynamicGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Edge.html#","e":false,"i":"","n":"Edge","t":"Edge[V](from: V, to: V, weight: Double)","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/Edge.html#@@-fffff69b","e":false,"i":"","n":"@@","t":"@@(w: Double): Edge[V]","d":"problemutils.classes.graphs.Edge","k":"def","x":""},
{"l":"problemutils/classes/graphs/Edge.html#reverse-0","e":false,"i":"","n":"reverse","t":"reverse: Edge[V]","d":"problemutils.classes.graphs.Edge","k":"val","x":""},
{"l":"problemutils/classes/graphs/Edge.html#u-0","e":false,"i":"","n":"u","t":"u: V","d":"problemutils.classes.graphs.Edge","k":"val","x":""},
{"l":"problemutils/classes/graphs/Edge.html#v-0","e":false,"i":"","n":"v","t":"v: V","d":"problemutils.classes.graphs.Edge","k":"val","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#","e":false,"i":"","n":"FiniteGraph","t":"FiniteGraph[V] extends Graph[V]","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#diff-fffff920","e":false,"i":"","n":"diff","t":"diff(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#edges-0","e":false,"i":"","n":"edges","t":"edges: Set[Edge[V]]","d":"problemutils.classes.graphs.FiniteGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#edgesFrom-0","e":false,"i":"","n":"edgesFrom","t":"edgesFrom: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.FiniteGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#edgesTo-0","e":false,"i":"","n":"edgesTo","t":"edgesTo: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.FiniteGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#excl-fffffde7","e":false,"i":"","n":"excl","t":"excl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#filterEdges-838","e":false,"i":"","n":"filterEdges","t":"filterEdges(p: Edge[V] => Boolean): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#filterVertices-838","e":false,"i":"","n":"filterVertices","t":"filterVertices(p: V => Boolean): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#incl-fffffde7","e":false,"i":"","n":"incl","t":"incl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#intersect-fffff920","e":false,"i":"","n":"intersect","t":"intersect(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#minimumSpanningGraph-0","e":false,"i":"","n":"minimumSpanningGraph","t":"minimumSpanningGraph: FiniteGraph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#totalCost-0","e":false,"i":"","n":"totalCost","t":"totalCost: Double","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#transpose-0","e":false,"i":"","n":"transpose","t":"transpose: FiniteGraph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#union-fffff920","e":false,"i":"","n":"union","t":"union(other: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph.html#vertices-0","e":false,"i":"","n":"vertices","t":"vertices: Set[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph$.html#","e":false,"i":"","n":"FiniteGraph","t":"FiniteGraph","d":"problemutils.classes.graphs","k":"object","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph$.html#apply-8de","e":false,"i":"","n":"apply","t":"apply[V](elems: Edge[V]*): FiniteGraph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph$.html#empty-fffff9a9","e":false,"i":"","n":"empty","t":"empty[V]: FiniteGraph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/FiniteGraph$.html#from-370","e":false,"i":"","n":"from","t":"from[V](elems: IterableOnce[Edge[V]]): FiniteGraph[V]","d":"problemutils.classes.graphs.FiniteGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#","e":false,"i":"","n":"Graph","t":"Graph[V]","d":"problemutils.classes.graphs","k":"trait","x":""},
{"l":"problemutils/classes/graphs/Graph.html#&-fffff920","e":false,"i":"","n":"&","t":"&(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#+-fffffde7","e":false,"i":"","n":"+","t":"+(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#--fffffde7","e":false,"i":"","n":"-","t":"-(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#\\-fffff920","e":false,"i":"","n":"\\","t":"\\(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#allPathsFrom-fffff081","e":false,"i":"","n":"allPathsFrom","t":"allPathsFrom(start: V): Set[Path[V]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#apply-fffff081","e":false,"i":"","n":"apply","t":"apply(v: V): Set[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#apply-fffffa63","e":false,"i":"","n":"apply","t":"apply(a: V, b: V): Option[Double]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#diff-fffff920","e":false,"i":"","n":"diff","t":"diff(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#edges-0","e":false,"i":"","n":"edges","t":"edges: Set[Edge[V]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#edgesFrom-0","e":false,"i":"","n":"edgesFrom","t":"edgesFrom: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#edgesTo-0","e":false,"i":"","n":"edgesTo","t":"edgesTo: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#excl-fffffde7","e":false,"i":"","n":"excl","t":"excl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#filterEdges-838","e":false,"i":"","n":"filterEdges","t":"filterEdges(p: Edge[V] => Boolean): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#filterVertices-838","e":false,"i":"","n":"filterVertices","t":"filterVertices(p: V => Boolean): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#incl-fffffde7","e":false,"i":"","n":"incl","t":"incl(e: Edge[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#intersect-fffff920","e":false,"i":"","n":"intersect","t":"intersect(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#reachableFrom-fffff081","e":false,"i":"","n":"reachableFrom","t":"reachableFrom(start: V): Set[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#shortestPath-fffff468","e":false,"i":"","n":"shortestPath","t":"shortestPath(start: V, end: V, heuristic: V => Double): Option[Path[V]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#shortestPathUntil-fffff3f0","e":false,"i":"","n":"shortestPathUntil","t":"shortestPathUntil(start: V, endPred: V => Boolean, heuristic: V => Double): Option[Path[V]]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#union-fffff920","e":false,"i":"","n":"union","t":"union(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#vertices-0","e":false,"i":"","n":"vertices","t":"vertices: Set[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph.html#|-fffff920","e":false,"i":"","n":"|","t":"|(g: Graph[V]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#","e":false,"i":"","n":"Graph","t":"Graph","d":"problemutils.classes.graphs","k":"object","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#apply-8de","e":false,"i":"","n":"apply","t":"apply[V](elems: (V, V)*): FiniteGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#empty-fffff098","e":false,"i":"","n":"empty","t":"empty[V]: Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#from-370","e":false,"i":"","n":"from","t":"from[V](edges: IterableOnce[Edge[V]]): FiniteGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#fromMap-fffff630","e":false,"i":"","n":"fromMap","t":"fromMap[V](map: Map[V, IterableOnce[V]]): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#fromMatrix-fffffa95","e":false,"i":"","n":"fromMatrix","t":"fromMatrix[V](matrix: Matrix[V], joined: (V, V) => Boolean, cost: (V, V) => Double): Graph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#fromTuples-370","e":false,"i":"","n":"fromTuples","t":"fromTuples[V](edges: IterableOnce[(V, V)]): FiniteGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#generate-b2c","e":false,"i":"","n":"generate","t":"generate[V](adjacencyFunction: V => IterableOnce[V]): ProceduralGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#generateLazily-fffff1d5","e":false,"i":"","n":"generateLazily","t":"generateLazily[V](adjacencyFunction: V => IterableOnce[V]): LazyGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#generateLazilyWith-fffff1d5","e":false,"i":"","n":"generateLazilyWith","t":"generateLazilyWith[V](adjacencyFunction: V => IterableOnce[Edge[V]]): LazyGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Graph$.html#generateWith-b2c","e":false,"i":"","n":"generateWith","t":"generateWith[V](adjacencyFunction: V => IterableOnce[Edge[V]]): ProceduralGraph[V]","d":"problemutils.classes.graphs.Graph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph.html#","e":false,"i":"","n":"LazyGraph","t":"LazyGraph[V] extends DynamicGraph[V]","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/LazyGraph.html#edges-0","e":false,"i":"","n":"edges","t":"edges: Set[Edge[V]]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph.html#edgesFrom-0","e":false,"i":"","n":"edgesFrom","t":"edgesFrom: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph.html#edgesTo-0","e":false,"i":"","n":"edgesTo","t":"edgesTo: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph.html#vertices-0","e":false,"i":"","n":"vertices","t":"vertices: Set[V]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph$.html#","e":false,"i":"","n":"LazyGraph","t":"LazyGraph","d":"problemutils.classes.graphs","k":"object","x":""},
{"l":"problemutils/classes/graphs/LazyGraph$.html#apply-fffff1d5","e":false,"i":"","n":"apply","t":"apply[V](adjacencyFunction: V => IterableOnce[V]): LazyGraph[V]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph$.html#from-fffff1d5","e":false,"i":"","n":"from","t":"from[V](adjacencyFunction: V => Set[Edge[V]]): LazyGraph[V]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/LazyGraph$.html#fromCost-fffff1d5","e":false,"i":"","n":"fromCost","t":"fromCost[V](adjacencyFunction: V => IterableOnce[(V, Double)]): LazyGraph[V]","d":"problemutils.classes.graphs.LazyGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Path.html#","e":false,"i":"","n":"Path","t":"Path[V](vertices: Seq[V], cost: Double)","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/Path.html#apply-0","e":false,"i":"","n":"apply","t":"apply: Int => V","d":"problemutils.classes.graphs.Path","k":"def","x":""},
{"l":"problemutils/classes/graphs/Path.html#head-0","e":false,"i":"","n":"head","t":"head: V","d":"problemutils.classes.graphs.Path","k":"def","x":""},
{"l":"problemutils/classes/graphs/Path.html#last-0","e":false,"i":"","n":"last","t":"last: V","d":"problemutils.classes.graphs.Path","k":"def","x":""},
{"l":"problemutils/classes/graphs/Path.html#reverse-0","e":false,"i":"","n":"reverse","t":"reverse: Path[V]","d":"problemutils.classes.graphs.Path","k":"val","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph.html#","e":false,"i":"","n":"ProceduralGraph","t":"ProceduralGraph[V] extends DynamicGraph[V]","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph.html#edges-0","e":false,"i":"","n":"edges","t":"edges: Set[Edge[V]]","d":"problemutils.classes.graphs.ProceduralGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph.html#edgesFrom-0","e":false,"i":"","n":"edgesFrom","t":"edgesFrom: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.ProceduralGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph.html#edgesTo-0","e":false,"i":"","n":"edgesTo","t":"edgesTo: Map[V, Set[Edge[V]]]","d":"problemutils.classes.graphs.ProceduralGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph.html#vertices-0","e":false,"i":"","n":"vertices","t":"vertices: Set[V]","d":"problemutils.classes.graphs.ProceduralGraph","k":"val","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph$.html#","e":false,"i":"","n":"ProceduralGraph","t":"ProceduralGraph","d":"problemutils.classes.graphs","k":"object","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph$.html#apply-b2c","e":false,"i":"","n":"apply","t":"apply[V](adjacencyFunction: V => IterableOnce[V]): ProceduralGraph[V]","d":"problemutils.classes.graphs.ProceduralGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph$.html#from-b2c","e":false,"i":"","n":"from","t":"from[V](adjacencyFunction: V => Set[Edge[V]]): ProceduralGraph[V]","d":"problemutils.classes.graphs.ProceduralGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/ProceduralGraph$.html#fromCost-b2c","e":false,"i":"","n":"fromCost","t":"fromCost[V](adjacencyFunction: V => IterableOnce[(V, Double)]): ProceduralGraph[V]","d":"problemutils.classes.graphs.ProceduralGraph","k":"def","x":""},
{"l":"problemutils/classes/graphs/Tree.html#","e":false,"i":"","n":"Tree","t":"Tree[V](value: V, children: Set[Tree[V]])","d":"problemutils.classes.graphs","k":"class","x":""},
{"l":"problemutils/classes/graphs/Tree.html#isSubtreeOf-95d","e":false,"i":"","n":"isSubtreeOf","t":"isSubtreeOf(other: Tree[V]): Boolean","d":"problemutils.classes.graphs.Tree","k":"def","x":""},
{"l":"problemutils/classes/graphs/Tree.html#vertices-0","e":false,"i":"","n":"vertices","t":"vertices: Set[V]","d":"problemutils.classes.graphs.Tree","k":"val","x":""},
{"l":"problemutils/classes/Cardinal.html#","e":false,"i":"","n":"Cardinal","t":"Cardinal(y: Int, x: Int)","d":"problemutils.classes","k":"enum","x":""},
{"l":"problemutils/classes/Cardinal.html#North-0","e":false,"i":"","n":"North","t":"North extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#NorthEast-0","e":false,"i":"","n":"NorthEast","t":"NorthEast extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#East-0","e":false,"i":"","n":"East","t":"East extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#SouthEast-0","e":false,"i":"","n":"SouthEast","t":"SouthEast extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#South-0","e":false,"i":"","n":"South","t":"South extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#SouthWest-0","e":false,"i":"","n":"SouthWest","t":"SouthWest extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#West-0","e":false,"i":"","n":"West","t":"West extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Cardinal.html#NorthWest-0","e":false,"i":"","n":"NorthWest","t":"NorthWest extends Cardinal","d":"problemutils.classes.Cardinal","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#","e":false,"i":"","n":"Hex","t":"Hex(q: Int, r: Int, s: Int)","d":"problemutils.classes","k":"enum","x":""},
{"l":"problemutils/classes/Hex.html#North-0","e":false,"i":"","n":"North","t":"North extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#NorthEast-0","e":false,"i":"","n":"NorthEast","t":"NorthEast extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#SouthEast-0","e":false,"i":"","n":"SouthEast","t":"SouthEast extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#South-0","e":false,"i":"","n":"South","t":"South extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#SouthWest-0","e":false,"i":"","n":"SouthWest","t":"SouthWest extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Hex.html#NorthWest-0","e":false,"i":"","n":"NorthWest","t":"NorthWest extends Hex","d":"problemutils.classes.Hex","k":"case","x":""},
{"l":"problemutils/classes/Matrix.html#","e":false,"i":"","n":"Matrix","t":"Matrix[A] extends IterableOnce[A]","d":"problemutils.classes","k":"class","x":""},
{"l":"problemutils/classes/Matrix.html#*-fffffd11","e":false,"i":"","n":"*","t":"*(other: Matrix[A])(using Numeric[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#+-fffffd11","e":false,"i":"","n":"+","t":"+(other: Matrix[A])(using Numeric[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#--fffffd11","e":false,"i":"","n":"-","t":"-(other: Matrix[A])(using Numeric[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#appendedBottom-e0","e":false,"i":"","n":"appendedBottom","t":"appendedBottom(other: Matrix[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#appendedLeft-e0","e":false,"i":"","n":"appendedLeft","t":"appendedLeft(other: Matrix[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#appendedRight-e0","e":false,"i":"","n":"appendedRight","t":"appendedRight(other: Matrix[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#appendedTop-e0","e":false,"i":"","n":"appendedTop","t":"appendedTop(other: Matrix[A]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#apply-4c5","e":false,"i":"","n":"apply","t":"apply(index: (Int, Int)): A","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#col-1b0","e":false,"i":"","n":"col","t":"col(col: Int): Vector[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#cols-0","e":false,"i":"","n":"cols","t":"cols: Vector[Vector[A]]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#count-db6","e":false,"i":"","n":"count","t":"count(f: A => Boolean): Int","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#determinant-c8","e":false,"i":"","n":"determinant","t":"determinant(using Numeric[A]): Double","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#determinantOption-fffffd6c","e":false,"i":"","n":"determinantOption","t":"determinantOption(using Numeric[A]): Option[Double]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#diagonal-0","e":false,"i":"","n":"diagonal","t":"diagonal: Vector[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#diagonalProduct-fffff142","e":false,"i":"","n":"diagonalProduct","t":"diagonalProduct(using Numeric[A]): A","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#dimensions-0","e":false,"i":"","n":"dimensions","t":"dimensions: (Int, Int)","d":"problemutils.classes.Matrix","k":"val","x":""},
{"l":"problemutils/classes/Matrix.html#dropCol-fffff71e","e":false,"i":"","n":"dropCol","t":"dropCol(col: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#dropRow-fffff71e","e":false,"i":"","n":"dropRow","t":"dropRow(row: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#exists-fffff66f","e":false,"i":"","n":"exists","t":"exists(f: A => Boolean): Boolean","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#filterCol-f74","e":false,"i":"","n":"filterCol","t":"filterCol(f: Vector[A] => Boolean): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#filterRow-f74","e":false,"i":"","n":"filterRow","t":"filterRow(f: Vector[A] => Boolean): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#find-94e","e":false,"i":"","n":"find","t":"find(pred: A => Boolean): Option[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#forall-fffff66f","e":false,"i":"","n":"forall","t":"forall(f: A => Boolean): Boolean","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#foreach-58c","e":false,"i":"","n":"foreach","t":"foreach[U](f: A => U): Unit","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#height-0","e":false,"i":"","n":"height","t":"height: Int","d":"problemutils.classes.Matrix","k":"val","x":""},
{"l":"problemutils/classes/Matrix.html#indexOutsideBounds-96e","e":false,"i":"","n":"indexOutsideBounds","t":"indexOutsideBounds(index: Pos2D): Boolean","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#indexWhere-94e","e":false,"i":"","n":"indexWhere","t":"indexWhere(pred: A => Boolean): Option[(Int, Int)]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#indices-0","e":false,"i":"","n":"indices","t":"indices: Matrix[(Int, Int)]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#isSquare-0","e":false,"i":"","n":"isSquare","t":"isSquare: Boolean","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#isSymmetric-0","e":false,"i":"","n":"isSymmetric","t":"isSymmetric: Boolean","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#map-265","e":false,"i":"","n":"map","t":"map[B](f: A => B): Matrix[B]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#mkString-0","e":false,"i":"","n":"mkString","t":"mkString: String","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#mkString-fffff2ca","e":false,"i":"","n":"mkString","t":"mkString(sep: String): String","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#mkString-fffff52f","e":false,"i":"","n":"mkString","t":"mkString(sep: String, rowSep: String): String","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#mkString-d94","e":false,"i":"","n":"mkString","t":"mkString(start: String, sep: String, end: String): String","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#oppositeDiagonal-0","e":false,"i":"","n":"oppositeDiagonal","t":"oppositeDiagonal: Vector[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#product-fffff142","e":false,"i":"","n":"product","t":"product(using Numeric[A]): A","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#range-0","e":false,"i":"","n":"range","t":"range: Matrix[Int]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#reshape-fffffec5","e":false,"i":"","n":"reshape","t":"reshape(height: Int, width: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#reverseCols-0","e":false,"i":"","n":"reverseCols","t":"reverseCols: Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#reverseRows-0","e":false,"i":"","n":"reverseRows","t":"reverseRows: Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#rotateLeft-0","e":false,"i":"","n":"rotateLeft","t":"rotateLeft: Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#rotateRight-0","e":false,"i":"","n":"rotateRight","t":"rotateRight: Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#row-1b0","e":false,"i":"","n":"row","t":"row(row: Int): Vector[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#rows-0","e":false,"i":"","n":"rows","t":"rows: Vector[Vector[A]]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#size-0","e":false,"i":"","n":"size","t":"size: Int","d":"problemutils.classes.Matrix","k":"val","x":""},
{"l":"problemutils/classes/Matrix.html#slice-fffff8d3","e":false,"i":"","n":"slice","t":"slice(index: (Int, Int))(height: Int, width: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#sum-fffff142","e":false,"i":"","n":"sum","t":"sum(using Numeric[A]): A","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#swapCols-fffffec5","e":false,"i":"","n":"swapCols","t":"swapCols(a: Int, b: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#swapRows-fffffec5","e":false,"i":"","n":"swapRows","t":"swapRows(a: Int, b: Int): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#toVector-0","e":false,"i":"","n":"toVector","t":"toVector: Vector[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#trace-fffff142","e":false,"i":"","n":"trace","t":"trace(using Numeric[A]): A","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#traceOption-fffffd6c","e":false,"i":"","n":"traceOption","t":"traceOption(using Numeric[A]): Option[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#transpose-0","e":false,"i":"","n":"transpose","t":"transpose: Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#updated-fffff152","e":false,"i":"","n":"updated","t":"updated(row: Int, col: Int)(value: A): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#width-0","e":false,"i":"","n":"width","t":"width: Int","d":"problemutils.classes.Matrix","k":"val","x":""},
{"l":"problemutils/classes/Matrix.html#zip-251","e":false,"i":"","n":"zip","t":"zip[B](other: Matrix[B]): Matrix[(A, B)]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#zipWithIndex-0","e":false,"i":"","n":"zipWithIndex","t":"zipWithIndex: Matrix[(A, Pos2D)]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix.html#zipWithRange-0","e":false,"i":"","n":"zipWithRange","t":"zipWithRange: Matrix[(A, Int)]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#","e":false,"i":"","n":"Matrix","t":"Matrix","d":"problemutils.classes","k":"object","x":""},
{"l":"problemutils/classes/Matrix$.html#apply-fffffc05","e":false,"i":"","n":"apply","t":"apply[A](height: Int, width: Int)(f: Pos2D => A): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#fill-fffff4a6","e":false,"i":"","n":"fill","t":"fill[A](height: Int, width: Int)(elem: => A): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#from-689","e":false,"i":"","n":"from","t":"from[A](input: Seq[Seq[A]]): Matrix[A]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#identity-fffff71e","e":false,"i":"","n":"identity","t":"identity(size: Int): Matrix[Int]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#range-2fe","e":false,"i":"","n":"range","t":"range(height: Int, width: Int, start: Int): Matrix[Int]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#rotation-56c","e":false,"i":"","n":"rotation","t":"rotation(rad: Double): Matrix[Double]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/classes/Matrix$.html#rotation-fffffc8e","e":false,"i":"","n":"rotation","t":"rotation(rad: Double, dir: Axis): Matrix[Double]","d":"problemutils.classes.Matrix","k":"def","x":""},
{"l":"problemutils/extensions.html#","e":false,"i":"","n":"problemutils.extensions","t":"problemutils.extensions","d":"","k":"package","x":""},
{"l":"problemutils/extensions.html#%-fffffc96","e":false,"i":"extension (tup: Pos2D)","n":"%","t":"%(other: Pos2D): (Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#+-fffffc96","e":false,"i":"extension (tup: Pos2D)","n":"+","t":"+(other: Pos2D): (Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#+-19","e":false,"i":"extension (v: Pos3D)","n":"+","t":"+(other: Pos3D): (Int, Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#--fffffc96","e":false,"i":"extension (tup: Pos2D)","n":"-","t":"-(other: Pos2D): (Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#--19","e":false,"i":"extension (v: Pos3D)","n":"-","t":"-(other: Pos3D): (Int, Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#->>-fffffe59","e":false,"i":"extension [V](a: V)","n":"->>","t":"->>(b: V): Edge[V]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#average-ffffff92","e":false,"i":"extension [A](xs: IterableOnce[A])","n":"average","t":"average(using Numeric[A]): Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#col-fffff835","e":false,"i":"extension (tup: Pos2D)","n":"col","t":"col: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#converge-be0","e":false,"i":"extension [A](a: A)","n":"converge","t":"converge(f: A => A): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#cross-fffff9b7","e":false,"i":"extension [A](xs: Vector[A])(implicit evidence$3: Numeric[A])","n":"cross","t":"cross(ys: Vector[A]): Vector[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#distance-fffff6fd","e":false,"i":"extension (tup: Pos2D)","n":"distance","t":"distance(other: Pos2D): Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#distance-a7f","e":false,"i":"extension (v: Pos3D)","n":"distance","t":"distance(other: Pos3D): Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#dl-364","e":false,"i":"extension (tup: Pos2D)","n":"dl","t":"dl: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#doUntil-637","e":false,"i":"extension [A](a: A)","n":"doUntil","t":"doUntil(f: A => A)(p: A => Boolean): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#dot-fffff7d3","e":false,"i":"extension [A](xs: Vector[A])(implicit evidence$2: Numeric[A])","n":"dot","t":"dot(ys: Vector[A]): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#down-364","e":false,"i":"extension (tup: Pos2D)","n":"down","t":"down: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#down-9e6","e":false,"i":"extension (v: Pos3D)","n":"down","t":"down: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#dr-364","e":false,"i":"extension (tup: Pos2D)","n":"dr","t":"dr: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#expand-fffff1bb","e":false,"i":"extension [A](a: A)","n":"expand","t":"expand(f: A => IterableOnce[A]): Set[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#findAllMatchWith-fffff048","e":false,"i":"extension (str: String)","n":"findAllMatchWith","t":"findAllMatchWith(regex: String): List[Match]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#findAllWith-fffff048","e":false,"i":"extension (str: String)","n":"findAllWith","t":"findAllWith(regex: String): List[String]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#findMatchWith-fffffa07","e":false,"i":"extension (str: String)","n":"findMatchWith","t":"findMatchWith(regex: String): Option[Match]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#findWith-fffffa07","e":false,"i":"extension (str: String)","n":"findWith","t":"findWith(regex: String): Option[String]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#flatten-251","e":false,"i":"extension [A](mat: Matrix[Matrix[A]])","n":"flatten","t":"flatten: Matrix[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#fst-5f7","e":false,"i":"","n":"fst","t":"fst[A, B](tup: (A, B)): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#getType-fffff404","e":false,"i":"extension [A](a: A)","n":"getType","t":"getType(implicit ct: ClassTag[A]): String","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#in-9e6","e":false,"i":"extension (v: Pos3D)","n":"in","t":"in: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#invert-982","e":false,"i":"extension [A, B](map: Map[A, B])","n":"invert","t":"invert: Map[B, Set[A]]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#iterate-ffffff0d","e":false,"i":"extension [A](a: A)","n":"iterate","t":"iterate(f: A => A)(n: Int): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#left-364","e":false,"i":"extension (tup: Pos2D)","n":"left","t":"left: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#left-9e6","e":false,"i":"extension (v: Pos3D)","n":"left","t":"left: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#lg-957","e":false,"i":"extension [A](a: A)","n":"lg","t":"lg: A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#log-957","e":false,"i":"extension [A](a: A)","n":"log","t":"log: A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#logAttr-fffffd97","e":false,"i":"extension [A](a: A)","n":"logAttr","t":"logAttr[B](f: A => B): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#logAttrIf-fa0","e":false,"i":"extension [A](a: A)","n":"logAttrIf","t":"logAttrIf[B](f: A => B)(p: B => Boolean): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#logCol-dbc","e":false,"i":"extension [A](a: A)","n":"logCol","t":"logCol(color: String): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#logIf-be0","e":false,"i":"extension [A](a: A)","n":"logIf","t":"logIf(p: A => Boolean): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#magnitude-fffff42e","e":false,"i":"extension [A](xs: Vector[A])","n":"magnitude","t":"magnitude: Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#manhattan-c43","e":false,"i":"extension (tup: Pos2D)","n":"manhattan","t":"manhattan(other: Pos2D): Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#manhattan-fffff801","e":false,"i":"extension (v: Pos3D)","n":"manhattan","t":"manhattan(other: Pos3D): Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#median-fffffb72","e":false,"i":"extension [A](xs: IterableOnce[A])","n":"median","t":"median(using Numeric[A], Ordering[A]): Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#move-744","e":false,"i":"extension (tup: Pos2D)","n":"move","t":"move(dir: Cardinal): Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#move-fffff51d","e":false,"i":"extension (v: Pos3D)","n":"move","t":"move(dir: Hex): (Int, Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighbours-6e0","e":false,"i":"extension (tup: Pos2D)","n":"neighbours","t":"neighbours: List[Pos2D]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighboursDiag-6e0","e":false,"i":"extension (tup: Pos2D)","n":"neighboursDiag","t":"neighboursDiag: List[Pos2D]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighboursDiagIn-fffffb8c","e":false,"i":"extension (tup: Pos2D)","n":"neighboursDiagIn","t":"neighboursDiagIn[A](using mat: Matrix[A]): List[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighboursIn-fffffb8c","e":false,"i":"extension (tup: Pos2D)","n":"neighboursIn","t":"neighboursIn[A](using mat: Matrix[A]): List[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighboursOrth-6e0","e":false,"i":"extension (tup: Pos2D)","n":"neighboursOrth","t":"neighboursOrth: List[Pos2D]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#neighboursOrthIn-fffffb8c","e":false,"i":"extension (tup: Pos2D)","n":"neighboursOrthIn","t":"neighboursOrthIn[A](using mat: Matrix[A]): List[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#normalized-482","e":false,"i":"extension [A](xs: Vector[A])","n":"normalized","t":"normalized: Vector[Double]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#out-9e6","e":false,"i":"extension (v: Pos3D)","n":"out","t":"out: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#padLeftTo-165","e":false,"i":"extension (str: String)","n":"padLeftTo","t":"padLeftTo(n: Int, char: Char): String","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#pipe-fffffd97","e":false,"i":"extension [A](a: A)","n":"pipe","t":"pipe[B](f: A => B): B","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#productBy-fffff34c","e":false,"i":"extension [A](xs: IterableOnce[A])","n":"productBy","t":"productBy[B](f: A => B)(using num: Numeric[B]): B","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#q-954","e":false,"i":"extension (v: Pos3D)","n":"q","t":"q: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#r-954","e":false,"i":"extension (v: Pos3D)","n":"r","t":"r: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#reshape-da9","e":false,"i":"extension [A](xs: Seq[A])","n":"reshape","t":"reshape(height: Int, width: Int): Matrix[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#right-364","e":false,"i":"extension (tup: Pos2D)","n":"right","t":"right: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#right-9e6","e":false,"i":"extension (v: Pos3D)","n":"right","t":"right: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#rms-ffffff92","e":false,"i":"extension [A](xs: IterableOnce[A])","n":"rms","t":"rms(using Numeric[A]): Double","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#row-fffff835","e":false,"i":"extension (tup: Pos2D)","n":"row","t":"row: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#rows-94d","e":false,"i":"extension (str: String)","n":"rows","t":"rows: List[String]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#s-954","e":false,"i":"extension (v: Pos3D)","n":"s","t":"s: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#snd-5f7","e":false,"i":"","n":"snd","t":"snd[A, B](tup: (A, B)): B","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#space-957","e":false,"i":"extension [A](a: A)","n":"space","t":"space: A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#split-fffff643","e":false,"i":"extension [A](xs: Seq[A])","n":"split","t":"split(elem: A): List[Seq[A]]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#sumBy-fffff34c","e":false,"i":"extension [A](xs: IterableOnce[A])","n":"sumBy","t":"sumBy[B](f: A => B)(using num: Numeric[B]): B","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#tap-be0","e":false,"i":"extension [A](a: A)","n":"tap","t":"tap(f: A => Unit): A","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toBoolean-ffffff99","e":false,"i":"extension (p: Int)","n":"toBoolean","t":"toBoolean: Boolean","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toInt-3c7","e":false,"i":"extension (p: Boolean)","n":"toInt","t":"toInt: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toMatrix-689","e":false,"i":"extension [A](vss: Seq[Seq[A]])","n":"toMatrix","t":"toMatrix: Matrix[A]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toVec3-fffff9c8","e":false,"i":"extension [A](xs: Vector[A])","n":"toVec3","t":"toVec3: (Int, Int, Int)","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toVector-ffffff05","e":false,"i":"extension (tup: Pos2D)","n":"toVector","t":"toVector: Vector[Int]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#toVector-324","e":false,"i":"extension (v: Pos3D)","n":"toVector","t":"toVector: Vector[Int]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#transpose-364","e":false,"i":"extension (tup: Pos2D)","n":"transpose","t":"transpose: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#ul-364","e":false,"i":"extension (tup: Pos2D)","n":"ul","t":"ul: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#up-364","e":false,"i":"extension (tup: Pos2D)","n":"up","t":"up: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#up-9e6","e":false,"i":"extension (v: Pos3D)","n":"up","t":"up: Pos3D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#ur-364","e":false,"i":"extension (tup: Pos2D)","n":"ur","t":"ur: Pos2D","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#words-94d","e":false,"i":"extension (str: String)","n":"words","t":"words: List[String]","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#x-fffff835","e":false,"i":"extension (tup: Pos2D)","n":"x","t":"x: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#x-954","e":false,"i":"extension (v: Pos3D)","n":"x","t":"x: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#y-fffff835","e":false,"i":"extension (tup: Pos2D)","n":"y","t":"y: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#y-954","e":false,"i":"extension (v: Pos3D)","n":"y","t":"y: Int","d":"problemutils.extensions","k":"def","x":""},
{"l":"problemutils/extensions.html#z-954","e":false,"i":"extension (v: Pos3D)","n":"z","t":"z: Int","d":"problemutils.extensions","k":"def","x":""}];